### ISSUE TITLE
Proposal: Events through NEAR logs 

### ISSUE THREAD

**Issue by evgenykuzyakov** [near/NEPs#130]
# Summary

We propose to support Ethereum-style Events through current UTF-8 logs by following a JSON format.

# Background

Currently, NEAR protocol supports logging from a smart contract. But these logs are mostly used for debugging purposes. The protocol restricts the log message to be a valid UTF-8 or UTF-16 string. Most contracts are using these logs to display a human readable messages to users by displaying them in various consoles, either in a JS console or in terminal for near-cli. They are also displayed in the Explorer for every execution.

Internally on the protocol level, we serialize logs as part of ExecutionOutcome for every executed action Receipt. So you can verify them in theory if you have the entire ExecutionOutcome.

On Ethereum, Events are displayed by block explorers and also allow developers to subscribe to them.

# Use-cases

If NEAR adapts Events through logs, then we can do the following:
- Pass machine information from contracts to a front-end, which can parse them and display events using a proper UI or formatting. The front-end can also react to the events.
- Indexer may parse all logs that are in JSON format and organize/index them, so the particular event can be queried later. For example:
    - If a fungible token standard defines Events then an indexer can have a list of all fungible tokens for a given user. E.g. `{"interface": "nep_21", "event": "on_receive", "sender": "alice", "receiver": "bob", "amount": "9001"}`. Means `bob` received a fun token.
    - An exchange can send another event for every swap, an indexer may index all exchange events.
    - Native EVM can potentially dump EVM events as well by encoding them in `base64` or `hex`. Like this `{"interface": "evm", "event": "event", "address": "0xDEADBEEF...", "data": "0xCAFEBABE..."}`

# Proposal

Create a standard schema for logs in JSON format. I suggest we request 2 fields:
- `interface` - for defining the contract/standard which emits this event
- `event` - the type of event.

The rest of the JSON can be in free form. An indexer will try to parse every `log` message from the `ExecutionOutcome` in JSON and can index events by `current_account_id`, `predecessor_id`, `interface` and `event`. And dump the raw JSON log message into the `value` field.

# Pros and Cons

### Pros

- No protocol changes required from the Runtime or NEAR SDK. It will work immediately. There are some limits on the number of logs and the length of each log, but they are very reasonable.
- JSON is self-descriptive schema, so no need to know the schema in order to parse the event.

### Cons

- This field (`log`) is currently used for other purposes. But they are mostly human-readable and don't start with curly bracket `{`
- We're limited by the number of events from contract and the length of each event. 
- We're limited to UTF-8 encoding.

**Comment by nearmax** [comment]
I suggest we make a protocol upgrade where we allow logs to not be UTF-8/16 encoded. This will allow dApp developers to use: UTF strings, JSON, and binary encoded data whenever they choose.

The problem with making JSON a standard is the following:
* It is very difficult to work with in Solidity. I am not even sure anyone would consider writing JSON parser is Solidity. Suppose one of bridge users decides to have a custom token connector (e.g. for custom contract calls). They won't be able to use logs for locking/unlocking/minting/burning;
* It might also be harder to work with in other blockchains, if we decide to bridge more than just Ethereum;
* It is error prone -- integers, complex structures might be accidentally misused by the users;
* Ethereum events are binary encoded using ABI so this is not consistent with Etheruem DevX.

Logs/events have two purposes: information and cryptographic provability. I suggest we always prioritize DevX of the latter one, since DevX of the former one can be taken care of by Applayer tools.

**Comment by abacabadabacaba** [comment]
I agree with @nearmax that we need less JSON, not more. I think that it was a mistake that we made smart contract parse JSON on-chain in the first place. We should definitely be using binary serialization in any new interfaces used or implemented by on-chain code.

**Comment by evgenykuzyakov** [comment]
We've already made a selection of JSON. There is no going back. 

It's interesting to consider introducing binary events just for ethereum. Borsh events doesn't have a schema, so the receiver has to know the schema of the event.

While we can make a protocol change to allow binary data in logs without schema, it's not going to help in any way for the indexer. Unless in addition to every standard we also define the borsh schema, we can't unify the experience.
Or every log is a particular binary format that is unified across contracts.

Also logs in the contracts are not merklized like in Ethereum, so you need a full log data in the ExecutionOutcome which seems not be feasible to achieve in Solidity side.

So to support them on Solidity we're likely need to introduce not only binary format for events but also a merklelization of such events. It's a much larger effort and only required on the Eth side.

While we're trying to solve a devX issue on NEAR side and don't need to worry about provability of such things.
The main benefit will be the ability by indexer to identify such log events and provide through the API. The short term goal is to get all tokens into the wallet.

**Comment by luciotato** [comment]
I think pros outweigh cons.
No changes to protocol sounds nice
JSON is natural since fn args are already JSON. It's easy to generate, and it's machine & user-readable
Since you're gonna remove from the logs strings starting with "{", maybe you can reserve also a leading char to recognize binary-base64 encoded "events" *in future expansions* of this idea: for example the base64 padding char "="
so: ´{"interface": "nep_21", "event": "on_receive", ...´  is a JSON event
while `=QW5kIHRoZXkgd2VyZSBhbGwgZnJlZQ==` is a binary base64-encoded event

Since bas64 is not so easy to generate, that can wait for an use case. At that point you can add `env::emitEventBinary(Vec<u8>)`

**Comment by miohtama** [comment]
I agree with @luciotato. Based on the historical evidence, once the format is locked down, or "recommended" it might become a lodestone. Ethereum went with its RLP encoding, in good and bad and getting to ABIv2 took forever.

Based on looking at the existing blockchain events, I assume most of the payload will be hexadecimal data: addresses and hashes. These are better to be presented in binary instead of string. They are, in fact, better to be handled in binary as well, as most programming languages support bytes types, fixed length or not, making it harder to confuse to other types and arguments.

There are basically two kind of event serialisation formats to choose

1) Structured data, or strict ABI definitions like RLP, Protobuf

2) Unstructured data, no data definitions and limit for keys and value types, like JSON, MessageBack 

Not sure if Borsch is 1 or 2.

For smart contract use cases, I would heavily recommend option 1. Because

- Smart contracts must define event types they are going to emit, in a standardised manner, hopefully in the source code with a nice decoration "This is the event structure for event named X"

- External programming languages, both dynamically and statically typed need to parse these events

Having a rigid type definitions in place will make parsing the events much easier. There is no guessing what fields may or may not be present in the event and what is their purpose. This makes integrating smart contracts inheritantly more **secure**. 

This would not be an issue if you deal with a single contract only. But most of the events will be standardised across contracts, like ERC-20 `Transfer`. (Before ERC-20 was getting popular, there were few non-standard Transfer events around and it was a lot of `if`s in the parsed code.)

We also have kind of a precendence when loosely defined ABIs caused loss of money (integrators where not aware of the feature or how it is supposed to work):

https://www.xrparcade.com/news/malicious-actors-exploiting-xrpl-partial-payment-feature-once-again/

My suggestion here is:

- Pick something that allows you to use interfaces (AssemblyScript) or structs (Rust) to define types

- Choose a structured binary serializer format that works for both smart contract languages (really for Rust, as I assume none exists for AssemblyScript) and has quite widespread suppor for programming languages

- This does not need to be a fixed choice: make it open ended so that smart contracts can choose to change their default serialization format in the past, or even do hand-optimized binary serialisation if needed

**Comment by miohtama** [comment]
For the reference, here is how Elrond does events (Rust, WebAssembly):

https://github.com/ElrondNetwork/sc-examples-rs/blob/master/simple-coin/src/lib.rs#L151

**Comment by frol** [comment]
So we are basically talking about a convention here, right? JSON is only one of the formats and given the suggestions to allow any format, we may as well just use base64-encoded data (you will be able to encode JSON just as well as anything else).

I wonder if we considered using cross-contracts calls API for the events. It sounds more appropriate to me than the text field. :thinking: 

Indexer-wise, it will be cumbersome to support the convention of logs parsing, but there is nothing that could prevent it.

> Not sure if Borsch is 1 or 2.

[Borsh](https://borsh.io) is a structured and strict ABI serialization format.

**Comment by evgenykuzyakov** [comment]
To summarize the current options:

## Option 1. Use JSON in existing log fields.

### Pros

- Can be launched immediately.
- Works OK with indexer, since the JSON is self-descriptive and we can just ask to have 2 fields for as indexes in DB for querying.

### Cons

- Doesn't work well with Solidity on Ethereum, because it requires parsing JSON.
- Has overhead of writing in JSON format

## Option 2. Expand existing logs to support Binary format (non UTF-8 strings)

### Pros

- Allows to use binary serializers, e.g. Borsh for events
- Each contract outputs structured logs.
- Can be parsed on Ethereum side if needed
- Minimum memory overhead - cheaper

### Cons

- Requires a protocol change.
- Will break existing bridge implementation and change light client spec due to change in ExecutionOutcome
- Such implementation will delay the feature release by a few months which will not be ready to use for current Bridge beta

## Option 3. Use existing logs with JSON, but also allow base64 for binary data

As suggested by @luciotato 

### Pros

- Pros from the **Option 1**
- Solidity/Ethereum may now parse them more efficiently due to ability to convert `base64` to a `borsh` format with minor overhead. 

### Cons

- Not as efficient as binary logs. `4/3` size comparing to binary.
- Decoding requires extra parsing.

**Comment by chadoh** [comment]
I'm currently focused on getting a usable Bridge by the end of 2020. Options 1 & 3 both seem fine for that. A couple things that aren't clear to me:

* If we go with 1 or 3 now, will it more difficult to upgrade to Option 2 in the future?
* Is it "1 xor 3"? Seems like maybe we could allow smart contract authors to choose whether to base64 encode their JSON or not, and require indexers & other apps to support both.

**Comment by evgenykuzyakov** [comment]
The option 3 is not different from an option 1. Question is whether option 3 works for current Eth-bridge needs.
I'm not sure how NEAR fungible tokens are transferred through the bridge to the Ethereum. E.g. what type of event we rely upon on Solidity part right now, since the Events question was never raised before. For this we need an input from @Kouprin

**Comment by nearmax** [comment]
@evgenykuzyakov 

> Will break existing bridge implementation and change light client spec due to change in ExecutionOutcome
> Such implementation will delay the feature release by a few months which will not be ready to use for current Bridge beta

I don't think it will, Strings are blobs are serialized exactly the same by Borsh with one difference that for Strings upon deserialization the blob is validating to be UTF. This change is backwards compatible from interface standpoint.

So the only downside of Option 2 is that it requires protocol change.

> Solidity/Ethereum may now parse them more efficiently due to ability to convert base64 to a borsh format with minor overhead.

Is the overhead going to be minor though?

**Comment by nearmax** [comment]
Also, AFAIR we merkelize logs differently from how Ethereum does it. We might want to revisit our logs structure and merkelization entirely, since Ethereum's design might be better. Also, we need to think how we will allow log subscription, similar to Ethereum.

**Comment by frol** [comment]
Just FYI, if we go with the binary logs will need to properly address this on JSON RPC side (the old field will become an empty string value, and the binary log will get a new name `logs_base64`)

**Comment by evgenykuzyakov** [comment]
> Just FYI, if we go with the binary logs will need to properly address this on JSON RPC side (the old field will become an empty string value, and the binary log will get a new name `logs_base64`)

I guess we have to introduce this field first and only after we migrate all tools we can stop returning the old one and switch it to be binary.

**Comment by evgenykuzyakov** [comment]
1) We change ExecutionOutcome to be store logs as `Vec<Vec<u8>>`
2) We change RPC to return `logs_base64` in addition to `logs`. And make `logs` to be `loss_from_ut8`
3) Patch nodes
4) Migrate all tools to new `logs_base_64`
5) Do a protocol upgrade to allow logging of non `utf-8` logs
6) Once nodes upgrade to new protocol. Add a SDK helper for logging.

**Comment by luciotato** [comment]
There are a lot of tools reading logs to give some information to the user (I'm processing the logs for example when there's an error to show something to the user). 
Initially you'll duplicate the info as `logs `and `logs_base64`? ?
The JSONRPC server will return garbage in `logs` if it's binary data? 

If this proposal is about events I recommend to leave logs as they are and create a new API exclusive for events with binary encoding and the minimal structure you proposed. 

Why break logs when what you want is events?

**Comment by nearmax** [comment]
@luciotato 
> Why change how logs are working when what you want is events?

Because logs and events should be the same thing. If we want to use logs for informational purposes only then we should stop merkelizing them.

@evgenykuzyakov 
> It still doesn't address the schema generalization issue for binary logs. We may want to introduce something like:
> ```rust
> pub struct Event {
>   /// Defines which type of contracts emitted this event. E.g. NEP_21 token may put `21` here.
>   /// Or we can use `interface_id` or `trait_id` and have separate document explaining standards. 
>   pub nep_id: u32,
>   /// Defines a type of event from the Trait. It can be a `Sent` or `Received` that the standard in the particular NEP defines.
>   /// If we think there can't be more than 255 event types per NEP_ID then we can limit it to `u8` and pass Enum internally
>   pub event_id: u32,
>   // The remaining is not part of a log standard and can be anything.
>   // The indexer can still decode it, since each log record has a known length.
>   // ....
> }
> ```

I am not sure this should be implemented on the protocol level, for two reasons:
* `nep_id` is not enforcable, contracts can lie, and so there is no reason to have it outside the binary blob on a protocol level;
* This information can exist as part of the binary log, similarly to how Eth contracts encode with ABI events. Ethereum DevX of events seems to be pretty good so there is no reason to create anything different.

**Comment by luciotato** [comment]
@nearmax I agree with you that logs should not be merkelized and should be used for informational purposes, and also be managed separately from events.

**Comment by frol** [comment]
[NEP-297](https://nomicon.io/Standards/EventsFormat) implemented log events quite some time ago, so I am closing this discussion
