### ISSUE TITLE
Document contract reward

### ISSUE THREAD

**Issue by bowenwang1996** [near/NEPs#198]
Whenever a contract method is called, the contract itself gets 30% of the gas burnt as a reward. This should be documented in the protocol spec.

**Comment by frol** [comment]
Sorry, I don't believe this is resolved.

* [ ] I believe the explanation of 30% of `gas_burnt_for_function_call` is relevant in that context, but it does not really cover this request as I cannot really point anybody to it and expect them to understand how exactly the concept of function call royalties work. I find this situation amusing since we implemented this feature to attract developers, but we don't really advertise it anywhere /cc @amgando @ilblackdragon @evgenykuzyakov 
* [ ] I still don't understand the mechanics, e.g. what gas price is used to reward the contract account? when the balance is expected to be updated (right during the receipt processing or after all the receipts are applied; I assume the former is the case, but I prefer explicitness, so I don't need to load the whole context to understand a single line of the doc)?

**Comment by bowenwang1996** [comment]
@frol your request seems to be about some higher level documentation. It is not the responsibility of reference-level documentation to advertise some feature and give a comprehensive overview of how it works. I believe your request is better suited for https://github.com/near/docs

**Comment by frol** [comment]
@bowenwang1996 I would expect to see this concept having its own section as it seems to be quite an independent concept of the NEAR Protocol. https://nomicon.io/Economics/README.html page looks the right place to mention it. Docs will come next, and indeed it will focus on teaching the concept and talking about how it can be used.

**Comment by bowenwang1996** [comment]
> I would expect to see this concept having its own section as it seems to be quite an independent concept of the NEAR Protocol

That is fair. @Longarithm could you add this to the Economics section as well?

**Comment by Longarithm** [comment]
Done, could you take a look?
