### ISSUE TITLE
NEP-177 (NFT Metadata) issued_at, expires_at, starts_at, updated_at confusing explanation

### ISSUE THREAD

**Issue by emarai** [near/NEPs#251]
I was writing a code on minting new NFT and wanted to include the issued_at metadata on-chain. The problem was it is not clear is it unix epoch or datetime.

https://github.com/near/NEPs/blob/master/specs/Standards/NonFungibleToken/Metadata.md#interface

In the interface, it is unix epoch in millisecond
 ```
  issued_at: string|null, // When token was issued or minted, Unix epoch in milliseconds
  expires_at: string|null, // When token expires, Unix epoch in milliseconds
  starts_at: string|null, // When token starts being valid, Unix epoch in milliseconds
  updated_at: string|null, // When token was last updated, Unix epoch in milliseconds
  ```
  
But if you scroll down below, there's another explanation showing that for every *_at metadata using ISO 8601 datetime.
```
issued_at: ISO 8601 datetime when token was issued or minted
expires_at: ISO 8601 datetime when token expires
starts_at: ISO 8601 datetime when token starts being valid
updated_at: ISO 8601 datetime when token was last updated
```

Which one is the right explanation?

**Comment by mikedotexe** [comment]
Thank you and yes, this is an oversight and sorry for the confusion. I think I will open this up to others as well. My thinking it is should be milliseconds, as this is easily obtainable using the block timestamp and dividing it. (Since the block timestamp is in nanoseconds) If we want it to be ISO 8601 it seems like all NFTs will need to have additional logic which would bloat storage of the smart contract. I believe frontends and other systems ingesting the data should do the work to transform the milliseconds epoch into a more friendly form.
